apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  ports:
  - name: "9021"
    port: 9021
    targetPort: 9021
  selector:
    io.kompose.service: control-center
status:
  loadBalancer: {}
