apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen
  name: ksql-datagen
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-datagen
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo Waiting for Kafka to be ready... && cub kafka-ready -b broker:29092
          1 40 && echo Waiting for Confluent Schema Registry to be ready... && cub
          sr-ready schema-registry 8081 40 && echo Waiting a few seconds for topic
          creation to finish... && sleep 11 && tail -f /dev/null
        env:
        - name: KSQL_CONFIG_DIR
          value: /etc/ksql
        - name: KSQL_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
        - name: STREAMS_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: STREAMS_SCHEMA_REGISTRY_HOST
          value: schema-registry
        - name: STREAMS_SCHEMA_REGISTRY_PORT
          value: "8081"
        image: confluentinc/ksql-examples:5.4.0
        name: ksql-datagen
        resources: {}
      hostname: ksql-datagen
      restartPolicy: Always
status: {}
