apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rest-proxy
    spec:
      containers:
      - env:
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: KAFKA_REST_HOST_NAME
          value: rest-proxy
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: http://schema-registry:8081
        image: confluentinc/cp-kafka-rest:5.4.0
        name: rest-proxy
        ports:
        - containerPort: 8082
        resources: {}
      hostname: rest-proxy
      restartPolicy: Always
status: {}
